config/routes.rb
Rails.application.routes.draw do
  get 'admin/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create ]
  end

  namespace :admin do
    resources :restaurants, only: [:destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant, presence: true
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def destroy
    @restaurant = Restaurant.find(restaurant_id)
    @restaurant.destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new # keeps user input to avoid writing everything again when error
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    # Longer way to access the reviews for a specifique restaurant
    # @review = Review.where(restaurant_id: params[:id])
    @reviews = @restaurant.reviews
  end

  def destroy
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
    # raise
  end

  def create
    restaurant_id = restaurant_params
    review_content = review_params[:content]
    review_rating = review_params[:rating].to_i

    @restaurant = Restaurant.find(restaurant_id)

    @review = Review.new(restaurant: @restaurant, content: review_content, rating: review_rating)
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new # keeps user input to avoid writing everything again when error
    end
  end

  private

  def review_params
    params.require(:review).permit(:restaurant, :content, :rating)
  end

  def restaurant_params
    params.require(:restaurant_id).to_i
  end
end

# THOSE ARE THE PARAMS SENT IN CREATE, HENCE 2 _PARAMS FUNCTIONS
# {"utf8"=>"✓",
#  "authenticity_token"=>"NtIEcUK/AiBGF6CsBprdZCsGuyoOqcGlCgKSEj38sE3GGVeTem9zkJNDaafmx/ePRdecgMRcnznv0PhV+DD04g==",
#  "review"=>{"restaurant"=>"La Creperie", "content"=>"Good", "rating"=>"5"},
#  "commit"=>"Add a review",
#  "restaurant_id"=>"2"}

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/destroy.html.erb
<h1>Admin#destroy</h1>
<p>Find me in app/views/admin/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- app/views/layouts/application.html.erb -->
    <!-- Add these line for detecting device width -->
    <!-- Adding a viewport in the layout -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/index.html.erb
<h1>RESTAURANT INDEX PAGE</h1>

<h3>Restaurants list below:</h3>

<table>
  <tbody>
    <tr>
      <th>Id</th>
      <th>Name</th>
    </tr>

    <% @restaurants.each do |restaurant|%>
      <tr>
        <td><%= restaurant.id%></td>
        <td><%= link_to "#{restaurant.name}", restaurant_path(restaurant)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Add a restaurant", new_restaurant_path, class: "btn btn-primary" %>

app/views/restaurants/new.html.erb
<h1>NEW RESTAURANT PAGE</h1>

<h3>Add a restaurant below:</h3>

<%= simple_form_for (@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit "Add a restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<h1>RESTAURANT SHOW PAGE</h1>

<h3>Restaurant details below:</h3>

<table>
  <tbody>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Address</th>
      <th>Phone Number</th>
      <th>Category</th>
    </tr>

    <tr>
      <td><%= @restaurant.id%></td>
      <td><%= @restaurant.name%></td>
      <td><%= @restaurant.address%></td>
      <td><%= @restaurant.phone_number%></td>
      <td><%= @restaurant.category%></td>
      <td><%= @restaurant.category%></td>
    </tr>
  </tbody>
</table>

<p></p>

<table>
  <tbody>
    <tr>
      <th>Rating</th>
      <th>Content</th>
    </tr>

    <% @reviews.each do |review|%>
      <tr>
        <td><%= review.rating%></td>
        <td><%= review.content%></td>
      </tr>
    <% end %>
  </tbody>

</table>

<p></p>
<p></p>
<p></p>

<%= link_to "Restaurants list", restaurants_path, class: "btn btn-primary" %>
<%= link_to "Add a review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>NEW REVIEW PAGE</h1>

<h3>Add a review below:</h3>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>